import "@radix-ui/themes/styles.css";
import './globals.css'
import './theme-config.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import { Theme, ThemePanel } from "@radix-ui/themes";


const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: 'Issue Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={inter.className}>
        <Theme accentColor="violet">
          <NavBar />
          <main className="px-5">
            {children}
          </main>
          <ThemePanel />
        </Theme>
      </body>
    </html>
  )
}
